# description of the peak project for atlas
type: project
name: peak
description: "A study of peak everything starting with population."
owner:
    name: dd
    email: 'nearwalden@gmail.com'
repos:
    git: "https://github.com/nearwalden/peak"
